source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/general/paths.vim
source $HOME/.config/nvim/plug-config/fzf.vim
source $HOME/.config/nvim/plug-config/dashboard-nvim.vim
source $HOME/.config/nvim/plug-config/signify.vim
source $HOME/.config/nvim/plug-config/lsp-config.vim
source $HOME/.config/nvim/plug-config/rust.vim
source $HOME/.config/nvim/plug-config/neoformat.vim
source $HOME/.config/nvim/plug-config/indent-blankline.vim
luafile $HOME/.config/nvim/themes/vscode.lua
luafile $HOME/.config/nvim/plug-config/lualine.lua
luafile $HOME/.config/nvim/plug-config/compe-config.lua
luafile $HOME/.config/nvim/plug-config/python-lsp.lua
luafile $HOME/.config/nvim/plug-config/clang-config.lua
luafile $HOME/.config/nvim/plug-config/neoscroll.lua
luafile $HOME/.config/nvim/plug-config/nvim-treesitter.lua
luafile $HOME/.config/nvim/plug-config/nvim-lspinstall.lua
luafile $HOME/.config/nvim/plug-config/lsp-rooter.lua
luafile $HOME/.config/nvim/plug-config/lsp-install.lua
luafile $HOME/.config/nvim/plug-config/trouble.lua
luafile $HOME/.config/nvim/plug-config/fterm.lua
luafile $HOME/.config/nvim/plug-config/kommentary.lua
luafile $HOME/.config/nvim/plug-config/nvim-tree.lua

